"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
[character]
format = "[\\$](green bold) "

[directory]
truncation_length = 3

[git_branch]
symbol = ''
format = '\([$symbol$branch(:$remote_branch)]($style)\)'

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = ''
ahead = ''
behind = ''
diverged = ''
up_to_date = 'âœ“'
untracked = ''
stashed = ''
modified = 'ğŸ”¥'
staged = ''
renamed = ''
deleted = ''

[package]
disabled = true

[nodejs]
disabled = true

[gcloud]
disabled = true

[aws]
format = ' [â˜ $profile(\($region\))]($style) '
style = 'bold yellow'
force_display = true

command_timeout = 6000

